# Generated by Django 3.1.7 on 2021-11-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0002_auto_20211112_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
